name: Maven Package, Docker build and push to registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build with Maven
        run: mvn package
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.ruscalworld.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.ruscalworld.ru/ruscalworld/pollbot:latest